<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260414043325 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE etablissement (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, nom VARCHAR(255) NOT NULL, adresse VARCHAR(255) NOT NULL, ville VARCHAR(255) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE evenement (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, titre VARCHAR(255) NOT NULL, description TEXT NOT NULL, date_debut TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, date_fin TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, lieu VARCHAR(255) NOT NULL, etablissement_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_B26681EFF631228 ON evenement (etablissement_id)');
        $this->addSql('CREATE TABLE evenement_utilisateur (evenement_id INT NOT NULL, utilisateur_id INT NOT NULL, PRIMARY KEY (evenement_id, utilisateur_id))');
        $this->addSql('CREATE INDEX IDX_8C897598FD02F13 ON evenement_utilisateur (evenement_id)');
        $this->addSql('CREATE INDEX IDX_8C897598FB88E14F ON evenement_utilisateur (utilisateur_id)');
        $this->addSql('CREATE TABLE evenement_filiere (evenement_id INT NOT NULL, filiere_id INT NOT NULL, PRIMARY KEY (evenement_id, filiere_id))');
        $this->addSql('CREATE INDEX IDX_2DD54A42FD02F13 ON evenement_filiere (evenement_id)');
        $this->addSql('CREATE INDEX IDX_2DD54A42180AA129 ON evenement_filiere (filiere_id)');
        $this->addSql('CREATE TABLE filiere (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, nom VARCHAR(255) NOT NULL, description TEXT NOT NULL, debouche VARCHAR(127) NOT NULL, niveau_requis VARCHAR(255) NOT NULL, etablissement_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_2ED05D9EFF631228 ON filiere (etablissement_id)');
        $this->addSql('CREATE TABLE id_int (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, email VARCHAR(180) NOT NULL, roles JSON NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_IDENTIFIER_EMAIL ON id_int (email)');
        $this->addSql('CREATE TABLE utilisateur (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, nom VARCHAR(255) NOT NULL, prenom VARCHAR(255) NOT NULL, email VARCHAR(255) NOT NULL, password VARCHAR(255) NOT NULL, role VARCHAR(50) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_1D1C63B3E7927C74 ON utilisateur (email)');
        $this->addSql('ALTER TABLE evenement ADD CONSTRAINT FK_B26681EFF631228 FOREIGN KEY (etablissement_id) REFERENCES etablissement (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE evenement_utilisateur ADD CONSTRAINT FK_8C897598FD02F13 FOREIGN KEY (evenement_id) REFERENCES evenement (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE evenement_utilisateur ADD CONSTRAINT FK_8C897598FB88E14F FOREIGN KEY (utilisateur_id) REFERENCES utilisateur (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE evenement_filiere ADD CONSTRAINT FK_2DD54A42FD02F13 FOREIGN KEY (evenement_id) REFERENCES evenement (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE evenement_filiere ADD CONSTRAINT FK_2DD54A42180AA129 FOREIGN KEY (filiere_id) REFERENCES filiere (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE filiere ADD CONSTRAINT FK_2ED05D9EFF631228 FOREIGN KEY (etablissement_id) REFERENCES etablissement (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE evenement DROP CONSTRAINT FK_B26681EFF631228');
        $this->addSql('ALTER TABLE evenement_utilisateur DROP CONSTRAINT FK_8C897598FD02F13');
        $this->addSql('ALTER TABLE evenement_utilisateur DROP CONSTRAINT FK_8C897598FB88E14F');
        $this->addSql('ALTER TABLE evenement_filiere DROP CONSTRAINT FK_2DD54A42FD02F13');
        $this->addSql('ALTER TABLE evenement_filiere DROP CONSTRAINT FK_2DD54A42180AA129');
        $this->addSql('ALTER TABLE filiere DROP CONSTRAINT FK_2ED05D9EFF631228');
        $this->addSql('DROP TABLE etablissement');
        $this->addSql('DROP TABLE evenement');
        $this->addSql('DROP TABLE evenement_utilisateur');
        $this->addSql('DROP TABLE evenement_filiere');
        $this->addSql('DROP TABLE filiere');
        $this->addSql('DROP TABLE id_int');
        $this->addSql('DROP TABLE utilisateur');
    }
}
