<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Add forum_reponse table and created_at to forum.
 */
final class Version_ForumReponse extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Add forum_reponse table and created_at column to forum';
    }

    public function up(Schema $schema): void
    {
        // Add created_at to forum (nullable for existing rows)
        $this->addSql('ALTER TABLE forum ADD created_at TIMESTAMP NULL');

        $this->addSql('UPDATE forum SET created_at = NOW() WHERE created_at IS NULL');

        // Create forum_reponse table
        $this->addSql('
            CREATE TABLE IF NOT EXISTS forum_reponse (
                id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,

                forum_id INT NOT NULL,
                auteur_id INT NOT NULL,
                contenu TEXT NOT NULL,

                created_at TIMESTAMP NOT NULL,

                PRIMARY KEY(id),


                CONSTRAINT FK_forum_reponse_forum FOREIGN KEY (forum_id) REFERENCES forum (id) ON DELETE CASCADE,
                CONSTRAINT FK_forum_reponse_auteur FOREIGN KEY (auteur_id) REFERENCES utilisateur (id) ON DELETE CASCADE
            )

        ');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE IF EXISTS forum_reponse');
        $this->addSql('ALTER TABLE forum DROP COLUMN created_at');
    }
}
