<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260510102509 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('DROP TABLE id_int');
        $this->addSql('ALTER TABLE article ADD image_path VARCHAR(255) DEFAULT NULL');
        $this->addSql('ALTER INDEX idx_article_filiere RENAME TO IDX_23A0E66180AA129');
        $this->addSql('ALTER INDEX idx_article_auteur RENAME TO IDX_23A0E6660BB6FE6');
        $this->addSql('ALTER INDEX idx_avis_mentor RENAME TO IDX_8F91ABF0DB403044');
        $this->addSql('ALTER INDEX idx_avis_auteur RENAME TO IDX_8F91ABF060BB6FE6');
        $this->addSql('ALTER TABLE etablissement ADD image_path VARCHAR(255) DEFAULT NULL');
        $this->addSql('ALTER TABLE evenement ADD image_path VARCHAR(255) DEFAULT NULL');
        $this->addSql('ALTER TABLE filiere ADD image_path VARCHAR(255) DEFAULT NULL');
        $this->addSql('ALTER TABLE forum ADD image_path VARCHAR(255) DEFAULT NULL');
        $this->addSql('ALTER INDEX idx_forum_filiere RENAME TO IDX_852BBECD180AA129');
        $this->addSql('ALTER INDEX idx_forum_auteur RENAME TO IDX_852BBECD60BB6FE6');
        $this->addSql('ALTER INDEX uniq_mentor_user RENAME TO UNIQ_801562DEFB88E14F');
        $this->addSql('ALTER INDEX idx_msg_exped RENAME TO IDX_B6BD307F10335F61');
        $this->addSql('ALTER INDEX idx_msg_dest RENAME TO IDX_B6BD307FA4F84F6E');
        $this->addSql('ALTER TABLE participant_evenement ALTER statut DROP DEFAULT');
        $this->addSql('ALTER INDEX idx_pe_event RENAME TO IDX_C824A73AFD02F13');
        $this->addSql('ALTER INDEX idx_pe_user RENAME TO IDX_C824A73AA76ED395');
        $this->addSql('ALTER INDEX idx_question_test RENAME TO IDX_B6F7494E1E5D0459');
        $this->addSql('ALTER TABLE rendez_vous ALTER statut DROP DEFAULT');
        $this->addSql('ALTER INDEX idx_rdv_eleve RENAME TO IDX_65E8AA0A5AB72B27');
        $this->addSql('ALTER INDEX idx_rdv_mentor RENAME TO IDX_65E8AA0A5B758C63');
        $this->addSql('ALTER INDEX idx_reponse_question RENAME TO IDX_5FB6DEC71E27F6BF');
        $this->addSql('ALTER INDEX idx_res_user RENAME TO IDX_7ECAF22DA76ED395');
        $this->addSql('ALTER INDEX idx_res_test RENAME TO IDX_7ECAF22D1E5D0459');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE id_int (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, email VARCHAR(180) NOT NULL, roles JSON NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX uniq_identifier_email ON id_int (email)');
        $this->addSql('ALTER TABLE article DROP image_path');
        $this->addSql('ALTER INDEX idx_23a0e6660bb6fe6 RENAME TO idx_article_auteur');
        $this->addSql('ALTER INDEX idx_23a0e66180aa129 RENAME TO idx_article_filiere');
        $this->addSql('ALTER INDEX idx_8f91abf0db403044 RENAME TO idx_avis_mentor');
        $this->addSql('ALTER INDEX idx_8f91abf060bb6fe6 RENAME TO idx_avis_auteur');
        $this->addSql('ALTER TABLE etablissement DROP image_path');
        $this->addSql('ALTER TABLE evenement DROP image_path');
        $this->addSql('ALTER TABLE filiere DROP image_path');
        $this->addSql('ALTER TABLE forum DROP image_path');
        $this->addSql('ALTER INDEX idx_852bbecd60bb6fe6 RENAME TO idx_forum_auteur');
        $this->addSql('ALTER INDEX idx_852bbecd180aa129 RENAME TO idx_forum_filiere');
        $this->addSql('ALTER INDEX uniq_801562defb88e14f RENAME TO uniq_mentor_user');
        $this->addSql('ALTER INDEX idx_b6bd307fa4f84f6e RENAME TO idx_msg_dest');
        $this->addSql('ALTER INDEX idx_b6bd307f10335f61 RENAME TO idx_msg_exped');
        $this->addSql('ALTER TABLE participant_evenement ALTER statut SET DEFAULT \'inscrit\'');
        $this->addSql('ALTER INDEX idx_c824a73aa76ed395 RENAME TO idx_pe_user');
        $this->addSql('ALTER INDEX idx_c824a73afd02f13 RENAME TO idx_pe_event');
        $this->addSql('ALTER INDEX idx_b6f7494e1e5d0459 RENAME TO idx_question_test');
        $this->addSql('ALTER TABLE rendez_vous ALTER statut SET DEFAULT \'en_attente\'');
        $this->addSql('ALTER INDEX idx_65e8aa0a5b758c63 RENAME TO idx_rdv_mentor');
        $this->addSql('ALTER INDEX idx_65e8aa0a5ab72b27 RENAME TO idx_rdv_eleve');
        $this->addSql('ALTER INDEX idx_5fb6dec71e27f6bf RENAME TO idx_reponse_question');
        $this->addSql('ALTER INDEX idx_7ecaf22da76ed395 RENAME TO idx_res_user');
        $this->addSql('ALTER INDEX idx_7ecaf22d1e5d0459 RENAME TO idx_res_test');
    }
}
