<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260509000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'TP4 - Mentor, Avis, RendezVous, Message, Forum, Test, Question, Reponse, ResultatTest, Article, ParticipantEvenement (PostgreSQL)';
    }

    public function up(Schema $schema): void
    {
        // ── Mentor ────────────────────────────────────────────────────────────
        $this->addSql('CREATE TABLE mentor (
            id              INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
            utilisateur_id  INT NOT NULL,
            bio             TEXT NOT NULL,
            specialite      VARCHAR(255) NOT NULL,
            experience      TEXT DEFAULT NULL,
            tarif           DOUBLE PRECISION NOT NULL,
            PRIMARY KEY(id)
        )');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_MENTOR_USER ON mentor (utilisateur_id)');
        $this->addSql('ALTER TABLE mentor ADD CONSTRAINT FK_MENTOR_UTILISATEUR FOREIGN KEY (utilisateur_id) REFERENCES utilisateur (id) NOT DEFERRABLE INITIALLY IMMEDIATE');

        // ── Avis ──────────────────────────────────────────────────────────────
        $this->addSql('CREATE TABLE avis (
            id           INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
            mentor_id    INT NOT NULL,
            auteur_id    INT NOT NULL,
            note         DOUBLE PRECISION NOT NULL,
            commentaire  TEXT NOT NULL,
            PRIMARY KEY(id)
        )');
        $this->addSql('CREATE INDEX IDX_AVIS_MENTOR ON avis (mentor_id)');
        $this->addSql('CREATE INDEX IDX_AVIS_AUTEUR ON avis (auteur_id)');
        $this->addSql('ALTER TABLE avis ADD CONSTRAINT FK_AVIS_MENTOR FOREIGN KEY (mentor_id) REFERENCES mentor (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE avis ADD CONSTRAINT FK_AVIS_AUTEUR FOREIGN KEY (auteur_id) REFERENCES utilisateur (id) NOT DEFERRABLE INITIALLY IMMEDIATE');

        // ── RendezVous ────────────────────────────────────────────────────────
        $this->addSql('CREATE TABLE rendez_vous (
            id            INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
            id_eleve_id   INT NOT NULL,
            id_mentor_id  INT NOT NULL,
            date          TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
            statut        VARCHAR(50) NOT NULL DEFAULT \'en_attente\',
            PRIMARY KEY(id)
        )');
        $this->addSql('CREATE INDEX IDX_RDV_ELEVE  ON rendez_vous (id_eleve_id)');
        $this->addSql('CREATE INDEX IDX_RDV_MENTOR ON rendez_vous (id_mentor_id)');
        $this->addSql('ALTER TABLE rendez_vous ADD CONSTRAINT FK_RDV_ELEVE  FOREIGN KEY (id_eleve_id)  REFERENCES utilisateur (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE rendez_vous ADD CONSTRAINT FK_RDV_MENTOR FOREIGN KEY (id_mentor_id) REFERENCES mentor (id)     NOT DEFERRABLE INITIALLY IMMEDIATE');

        // ── Message ───────────────────────────────────────────────────────────
        $this->addSql('CREATE TABLE message (
            id               INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
            expediteur_id    INT NOT NULL,
            destinataire_id  INT NOT NULL,
            contenu          TEXT NOT NULL,
            PRIMARY KEY(id)
        )');
        $this->addSql('CREATE INDEX IDX_MSG_EXPED ON message (expediteur_id)');
        $this->addSql('CREATE INDEX IDX_MSG_DEST  ON message (destinataire_id)');
        $this->addSql('ALTER TABLE message ADD CONSTRAINT FK_MSG_EXPED FOREIGN KEY (expediteur_id)   REFERENCES utilisateur (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE message ADD CONSTRAINT FK_MSG_DEST  FOREIGN KEY (destinataire_id) REFERENCES utilisateur (id) NOT DEFERRABLE INITIALLY IMMEDIATE');

        // ── Forum ─────────────────────────────────────────────────────────────
        $this->addSql('CREATE TABLE forum (
            id         INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
            filiere_id INT NOT NULL,
            auteur_id  INT NOT NULL,
            titre      VARCHAR(255) NOT NULL,
            contenu    TEXT NOT NULL,
            PRIMARY KEY(id)
        )');
        $this->addSql('CREATE INDEX IDX_FORUM_FILIERE ON forum (filiere_id)');
        $this->addSql('CREATE INDEX IDX_FORUM_AUTEUR  ON forum (auteur_id)');
        $this->addSql('ALTER TABLE forum ADD CONSTRAINT FK_FORUM_FILIERE FOREIGN KEY (filiere_id) REFERENCES filiere    (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE forum ADD CONSTRAINT FK_FORUM_AUTEUR  FOREIGN KEY (auteur_id)  REFERENCES utilisateur(id) NOT DEFERRABLE INITIALLY IMMEDIATE');

        // ── Test ──────────────────────────────────────────────────────────────
        $this->addSql('CREATE TABLE test (
            id          INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
            titre       VARCHAR(255) NOT NULL,
            description TEXT NOT NULL,
            date        TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
            duree       INT DEFAULT NULL,
            PRIMARY KEY(id)
        )');

        // ── Question ──────────────────────────────────────────────────────────
        $this->addSql('CREATE TABLE question (
            id      INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
            test_id INT NOT NULL,
            contenu TEXT NOT NULL,
            PRIMARY KEY(id)
        )');
        $this->addSql('CREATE INDEX IDX_QUESTION_TEST ON question (test_id)');
        $this->addSql('ALTER TABLE question ADD CONSTRAINT FK_QUESTION_TEST FOREIGN KEY (test_id) REFERENCES test (id) NOT DEFERRABLE INITIALLY IMMEDIATE');

        // ── Reponse ───────────────────────────────────────────────────────────
        $this->addSql('CREATE TABLE reponse (
            id          INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
            question_id INT NOT NULL,
            contenu     TEXT NOT NULL,
            PRIMARY KEY(id)
        )');
        $this->addSql('CREATE INDEX IDX_REPONSE_QUESTION ON reponse (question_id)');
        $this->addSql('ALTER TABLE reponse ADD CONSTRAINT FK_REPONSE_QUESTION FOREIGN KEY (question_id) REFERENCES question (id) NOT DEFERRABLE INITIALLY IMMEDIATE');

        // ── ResultatTest ──────────────────────────────────────────────────────
        $this->addSql('CREATE TABLE resultat_test (
            id      INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
            user_id INT NOT NULL,
            test_id INT NOT NULL,
            score   DOUBLE PRECISION NOT NULL,
            date    TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
            PRIMARY KEY(id)
        )');
        $this->addSql('CREATE INDEX IDX_RES_USER ON resultat_test (user_id)');
        $this->addSql('CREATE INDEX IDX_RES_TEST ON resultat_test (test_id)');
        $this->addSql('ALTER TABLE resultat_test ADD CONSTRAINT FK_RES_USER FOREIGN KEY (user_id) REFERENCES utilisateur (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE resultat_test ADD CONSTRAINT FK_RES_TEST FOREIGN KEY (test_id) REFERENCES test        (id) NOT DEFERRABLE INITIALLY IMMEDIATE');

        // ── Article ───────────────────────────────────────────────────────────
        $this->addSql('CREATE TABLE article (
            id             INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
            filiere_id     INT NOT NULL,
            auteur_id      INT NOT NULL,
            titre          VARCHAR(255) NOT NULL,
            contenu        TEXT NOT NULL,
            date_creation  TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
            PRIMARY KEY(id)
        )');
        $this->addSql('CREATE INDEX IDX_ARTICLE_FILIERE ON article (filiere_id)');
        $this->addSql('CREATE INDEX IDX_ARTICLE_AUTEUR  ON article (auteur_id)');
        $this->addSql('ALTER TABLE article ADD CONSTRAINT FK_ARTICLE_FILIERE FOREIGN KEY (filiere_id) REFERENCES filiere    (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE article ADD CONSTRAINT FK_ARTICLE_AUTEUR  FOREIGN KEY (auteur_id)  REFERENCES utilisateur(id) NOT DEFERRABLE INITIALLY IMMEDIATE');

        // ── ParticipantEvenement ──────────────────────────────────────────────
        $this->addSql('CREATE TABLE participant_evenement (
            id                INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
            evenement_id      INT NOT NULL,
            user_id           INT NOT NULL,
            date_inscription  TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
            statut            VARCHAR(50) NOT NULL DEFAULT \'inscrit\',
            PRIMARY KEY(id)
        )');
        $this->addSql('CREATE INDEX IDX_PE_EVENT ON participant_evenement (evenement_id)');
        $this->addSql('CREATE INDEX IDX_PE_USER  ON participant_evenement (user_id)');
        $this->addSql('ALTER TABLE participant_evenement ADD CONSTRAINT FK_PE_EVENT FOREIGN KEY (evenement_id) REFERENCES evenement  (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE participant_evenement ADD CONSTRAINT FK_PE_USER  FOREIGN KEY (user_id)      REFERENCES utilisateur (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE rendez_vous          DROP CONSTRAINT FK_RDV_MENTOR');
        $this->addSql('ALTER TABLE avis                  DROP CONSTRAINT FK_AVIS_MENTOR');
        $this->addSql('ALTER TABLE reponse               DROP CONSTRAINT FK_REPONSE_QUESTION');
        $this->addSql('ALTER TABLE question              DROP CONSTRAINT FK_QUESTION_TEST');
        $this->addSql('ALTER TABLE resultat_test         DROP CONSTRAINT FK_RES_TEST');
        $this->addSql('DROP TABLE participant_evenement');
        $this->addSql('DROP TABLE article');
        $this->addSql('DROP TABLE resultat_test');
        $this->addSql('DROP TABLE reponse');
        $this->addSql('DROP TABLE question');
        $this->addSql('DROP TABLE test');
        $this->addSql('DROP TABLE forum');
        $this->addSql('DROP TABLE message');
        $this->addSql('DROP TABLE rendez_vous');
        $this->addSql('DROP TABLE avis');
        $this->addSql('DROP TABLE mentor');
    }
}
